name: Testes Unitarios

on:
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Executar testes
        run: node tests/testes.js
